name: TCS Daily Signal

on:
  schedule:
    - cron: "50 22 * * *"   # 매일 KST 오전 7시 50분 실행 (UTC 기준 22:50)
  workflow_dispatch: {}      # 수동 실행 버튼도 가능

jobs:
  run-tcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run notifier
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python TCS_Alert.py
