name: TCS daily

on:
  schedule:
    - cron: "50 22 * * *"   # UTC 22:50 = KST 07:50
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run TCS (yf→AV→Stooq)
        env:
          TELEGRAM_TOKEN:    ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT:     ${{ secrets.TELEGRAM_CHAT }}
          ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
          PROXY_URL:         ${{ secrets.PROXY_URL }}   # 선택 (없으면 빈값)
        run: |
          python TCS_Alert.py
