name: TCS Daily

on:
  schedule:
    - cron: "50 22 * * *"   # UTC 22:50 = KST 07:50
  workflow_dispatch:        # 수동 실행 버튼

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York   # 로그/시간대 일관성

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run TCS Alert
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT:  ${{ secrets.TELEGRAM_CHAT }}
        run: |
          python TCS_Alert.py
