name: TCS daily

on:
  schedule:
    # 07:50 KST == 22:50 UTC (전날). 월~금만.
    - cron: '50 22 * * 1-5'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      PYTHONUNBUFFERED: "1"   # 실시간 로그 출력
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # zoneinfo 내장, 최신 ssl

      - name: Env sanity check (length only)
        run: |
          python --version
          echo "TOKEN length = ${#TELEGRAM_TOKEN}"
          echo "CHAT  length = ${#TELEGRAM_CHAT_ID}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run notifier
        run: python TCS_Alert.py
