name: TCS daily

on:
  schedule:
    - cron: "50 22 * * *"   # UTC 22:50 = KST 07:50
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # (선택) 키가 주입됐는지 최소 확인용 — 실제 키는 마스킹됨
      - name: Check secrets presence
        env:
          FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}
        run: |
          if [ -z "${FINNHUB_KEY}" ]; then echo "NO FINNHUB_KEY"; exit 1; else echo "FINNHUB_KEY set"; fi

      - name: Run TCS
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT:  ${{ secrets.TELEGRAM_CHAT }}
          FINNHUB_KEY:    ${{ secrets.FINNHUB_KEY }}
          PROXY_URL:      ${{ vars.PROXY_URL }}  # 있으면 사용, 없으면 빈값
        run: |
          python TCS_Alert.py
