name: TCS Daily

on:
  schedule:
    - cron: "50 22 * * *"   # UTC 22:50 = KST 07:50
  workflow_dispatch:        # 수동 실행 버튼

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug env (1회)
        run: |
          python -c "import sys, os; print('PY', sys.version); print('TZ', os.environ.get('TZ'));"

      - name: Run TCS
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
        run: |
          python TCS_Alert.py
